name: Bump version

on:
  workflow_dispatch:
jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.repository != 'quintenroets/python-package-template'
    permissions:
      contents: write  # Repository will be modified
    steps:
    - name: Bump version
      uses: quintenroets/package-dev-tools/actions/bump-version@main
